### ISSUE TITLE
This SDK should work for both browser and node.js

### ISSUE THREAD

**Issue by nomagick** [jina-ai/jinaai-js#6]
So don't rely on node.js features like fs etc.

**Comment by email1230321** [comment]
While it functions seamlessly within a NodeJS environment, its compatibility encounters a hurdle when attempting to integrate with frontend frameworks such as Angular and Vue.js. We kindly request clarification regarding its frontend compatibility

**Comment by redjson** [comment]
We published a new version for browser support. An frontend integration example can be found here: https://github.com/jina-ai/jinaai-js/tree/main/examples/ts-examples/vuejs-integration
